server.port=8686
server.servlet.context-path=/aman
# Application
spring.application.name=A-Man
spring.application.version=1.4.2
spring.application.description=Docments for Asset-ERP

# 2. 대용량 마크다운 및 파일 업로드 제한 해제 (중요)
# 매뉴얼 시스템 특성상 이미지나 첨부파일, 큰 마크다운 텍스트가 들어오므로 제한을 넉넉히 늘려줍니다.
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
